# SCREEN CONFIGURATION
SCREEN_WIDTH = 100
SCREEN_HEIGHT = 100
FULLSCREEN = False

# CAMERA CONFIGURATION
CAMERA_COORDINATES = (0, 0, 0)
HORIZONTAL_VIEWING_ANGLE = 90
VERTICAL_VIEWING_ANGLE = 90
HORIZONTAL_ROTATION = 0
